# Generated by Django 4.2.3 on 2023-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_books_title_alter_films_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='films',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='readedbooks',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='series',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='watchedfilms',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='watchedseries',
            name='img_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='readedbooks',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchedseries',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
