# Generated by Django 4.2.3 on 2023-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_books_img_url_films_img_url_readedbooks_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='films',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='readedbooks',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='series',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='watchedseries',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
